import type { Category } from '@/data/types';

export const categories: Category[] = [
  {
    id: 'primary-contacts',
    title: 'Who to Contact First',
    description: 'The first calls your family should make',
    guidance: 'Start with one primary contact — the person who should be called first. Then add backup contacts like your attorney, financial advisor, or close friends who can help.',
    icon: '📞',
    ionIcon: 'call-outline',
    route: '/contacts',
    stateKey: 'contacts',
    filterType: 'primary',
  },
  {
    id: 'other-contacts',
    title: 'Important People',
    description: 'Everyone else your family should know about',
    guidance: 'Add other important people like neighbors, friends, employers, or anyone else who should be notified.',
    icon: '👤',
    ionIcon: 'person-outline',
    route: '/contacts',
    stateKey: 'contacts',
    filterType: 'secondary',
  },
  {
    id: 'finances',
    title: 'Financial Accounts',
    description: 'Bank, investment, and retirement accounts',
    guidance: 'List your bank accounts, investments, and any debts. You don\'t need account numbers — just enough detail so your family knows where to look.',
    icon: '💰',
    ionIcon: 'cash-outline',
    route: '/finances',
    stateKey: 'finances',
  },
  {
    id: 'insurance',
    title: 'Insurance Policies',
    description: 'Coverage your family should know about',
    guidance: 'Include life insurance first, then health, home, and auto policies. Note the provider and policy number so claims can be filed.',
    icon: '🛡️',
    ionIcon: 'shield-outline',
    route: '/insurance',
    stateKey: 'insurance',
  },
  {
    id: 'documents',
    title: 'Legal Documents',
    description: 'Wills, trusts, and important papers',
    guidance: 'Record where your will, trust, and power of attorney documents are stored. Include who has copies and how to access them.',
    icon: '📄',
    ionIcon: 'document-text-outline',
    route: '/documents',
    stateKey: 'documents',
  },
  {
    id: 'home-responsibilities',
    title: 'Property & Vehicles',
    description: 'Real estate, vehicles, and physical assets',
    guidance: 'Think about what would need attention if you weren\'t here — property, vehicles, or recurring obligations that someone would need to handle.',
    icon: '🏠',
    ionIcon: 'home-outline',
    route: '/home-responsibilities',
    stateKey: 'homeResponsibilities',
  },
  {
    id: 'pets',
    title: 'Pets',
    description: 'Care instructions for your animal companions',
    guidance: 'Include each pet\'s care needs, veterinarian information, and who has agreed to care for them. This ensures they\'re looked after by someone who knows what they need.',
    icon: '🐾',
    ionIcon: 'paw-outline',
    route: '/pets',
    stateKey: 'pets',
  },
  {
    id: 'digital-access',
    title: 'Digital Access',
    description: 'How to access your online accounts',
    guidance: 'List your important digital accounts and how to access them. Focus on critical accounts like email and password managers first. Don\'t store passwords here — just note where they can be found.',
    icon: '💻',
    ionIcon: 'laptop-outline',
    route: '/digital',
    stateKey: 'digitalAccounts',
  },
];
